  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes" />
  <meta name="format-detection" content="telephone=no" />
  <link rel="shortcut icon" href="/shared/img/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" href="/shared/img/apple-touch-icon.png" />
  <!-- og -->
  <meta property="og:type" content="website" />
  <meta property="og:image" content="" />
  <meta property="og:site_name" content="" />
  <meta property="og:locale" content="ja_JP" />
  <meta property="fb:app_id" content="" />